### ISSUE TITLE
Update-AssemblyVersion adds new-lines to the end of files

### ISSUE THREAD

**Issue by ChrisLambrou** [red-gate/RedGate.Build#23]
It seems that `Update-AssemblyVersion` is adding sneaky extra lines of white-space to the end of the updated source file. This was being masked by a test that was accounting for behaviour in an earlier incarnation of the implementation.

Originally reported by @richardjm

**Comment by nyctef** [comment]
Is this http://stackoverflow.com/questions/35279848/prevent-trailing-newline-in-powershell-out-file-command?

**Comment by richardjm** [comment]
Write a PR and remove Trim() to find out :)

**Comment by ChrisLambrou** [comment]
The more I work with PowerShell, the more I get pissed off with `Get-Content` and 'Out-File`. I think I'll resort to using `File.ReadAllText` and `File.WriteAllText` instead. I can also fix a BOM issue, too.

**Comment by richardjm** [comment]
Resolved with the PR

**Comment by ChrisLambrou** [comment]
Glad it helps. Please keep the branch open, though. I want to write some more tests. :)

**Comment by richardjm** [comment]
Can you create a new branch from experience github doesn't like to take two PRs from the same branch - especially if it was recreated. Can't see a way to un-delete it from github.

**Comment by ChrisLambrou** [comment]
Okay, will do.
