### ISSUE TITLE
Issues with Zip-Files

### ISSUE THREAD

**Issue by ChrisLambrou** [red-gate/RedGate.Build#7]
There are a couple of issues with the Zip-Files cmdlet.

1. The whole Verb-Noun thing. It should probably be called New-ZipFile or New-ZipArchive, or some other such thing.
2. Internally it uses 7-zip. If we're happy to target PowerShell 4 or later, then .NET 4.5 comes with a ZipFile class that has the same functionality. If we target PowerShell 3, then .NET 4 still has zip file support, albeit slightly more involved to consume. Perhaps we should ditch 7-zip as a dependency.

Any thoughts, @nyctef and @nicolasvan ?

**Comment by nyctef** [comment]
In general I'd prefer a pure powershell implementation, I think. Depending on .NET is okay, and depending on third-party libraries feels kinda messy unless it's really necessary.

Unzipping files with the shell is fairly straightforward:
```ps
function Unzip($zipPath, $destinationPath) {
    Write-Host "Unzipping $zipPath to $destinationPath"
    $shell = new-object -com shell.application
    $zip = $shell.NameSpace($zipPath)
    $destination = $shell.Namespace($destinationPath)
    foreach($item in $zip.items())
    {
        $destination.copyhere($item)
    }
}
```

Creating zip files is a bit more involved, but it looks like there's a neat way to do it [described here](http://mow001.blogspot.co.uk/2006/01/msh-out-zip-function.html):
```ps
function out-zip { 
  Param([string]$path) 

  if (-not $path.EndsWith('.zip')) {$path += '.zip'} 

  if (-not (test-path $path)) { 
    set-content $path ("PK" + [char]5 + [char]6 + ("$([char]0)" * 18)) 
  } 
  $ZipFile = (new-object -com shell.application).NameSpace($path) 
  $input | foreach {$zipfile.CopyHere($_.fullname)} 
}
```
This appears to work by creating an [empty zip file](https://en.wikipedia.org/wiki/Zip_(file_format)#Limits) if it doesn't already exist, and then using the shell to copy files into it. It might be nice if it could accept file contents as well as file paths, and it might have some issues with preserving directory structure, but it should work with any .NET/PS version, I think. I like the way this one is pipelineable, but it might be easier just to go with a .NET implementation.

**Comment by nicolasvan** [comment]
My experience is that 7zip is much faster at zipping big files (multithreading support). (but then should we need to zip big files?)

I also had bad experience with using the shell to zip unzip. mostly around when stuff doesn't work, the error messages / exit code are less than helpful....


It's good to see you guys improving RedGate.Build, but maybe we should focus on adding new functionallity ? (.e.g make it more useful instead of making it more perfect?)

**Comment by nyctef** [comment]
Yeah, this probably isn't the most important thing to work on

**Comment by nicolasvan** [comment]
I hope I'm not being a dick, I really appreciate the time you guys are spending on this :).

Maybe we could get one of your project and get it to use RedGate.Build ? Then we can improve RedGate.Build as we go ?

**Comment by nyctef** [comment]
Well, the Compare repos are already using a bunch of stuff from RedGate.Build - I just recently moved over to using new `Invoke-SigningService` in the UI, so now we don't have annoying file locking problems on `RedGate.MSBuild.Tasks.dll` :clap:

**Comment by ChrisLambrou** [comment]
I'm using it in DLMAutomationShared (currently empty, alas) and planning to use it in SQL Release.

> I hope I'm not being a dick.

Not at all. My main interest here is actually the name change. I think it's the only remaining cmdlet that causes a build warning on import.

The dependency on 7-zip is fine, currently works, has multi-threaded performance (more useful locally than on the build agents), and it unlikely to give us maintenance issues. I don't have any experience of how gracefully it fails, but that that's also true of using the .NET framework classes to do this, so meh.

**Comment by nicolasvan** [comment]
cool :relieved: feel free to change the name.
It's only used in the SmartAssembly repo, and I can update the name next time we upgrade RedGate.Build over there.
