### ISSUE TITLE
Delete branch after successful auto-merge

### ISSUE THREAD

**Issue by samblackburn** [red-gate/RedGate.Build#82]
It would be nice if the auto-merge feature didn't leave the branch lying around.

Looks like someone has made this work:
https://stackoverflow.com/questions/47455942/github-enterprise-api-delete-branch-after-merge

**Comment by samblackburn** [comment]
Requested by @nyctef

**Comment by samblackburn** [comment]
Also requested by Asha

**Comment by PeterGerrard** [comment]
Addressed in #89
